
import Link from 'next/link';
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from '@/components/ui/breadcrumb';

export default function SitemapPage() {
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://wiru.app';
  const pages = [
    { path: '/', name: 'Home', priority: '1.0', description: 'The main landing page of Wiru.app.' },
    { path: '/templates', name: 'Templates', priority: '0.9', description: 'Browse all available website and application templates.' },
    { path: '/#services', name: 'Services', priority: '0.8', description: 'Learn about our custom development services.' },
    { path: '/#about', name: 'About Us', priority: '0.8', description: 'Find out more about Wiru.app and our mission.' },
  ];

  return (
    <section className="py-12 md:py-16 lg:py-20 bg-background">
      <div className="container mx-auto px-4 md:px-6">
        <Breadcrumb className="mb-8">
          <BreadcrumbList>
            <BreadcrumbItem>
              <BreadcrumbLink asChild>
                <Link href="/">Home</Link>
              </BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbPage>Sitemap</BreadcrumbPage>
            </BreadcrumbItem>
          </BreadcrumbList>
        </Breadcrumb>
        <div className="text-center mb-12">
          <h1 className="text-4xl font-headline font-bold text-primary mb-4">Website Sitemap</h1>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            This page provides an overview of the Wiru.app website structure for easy navigation.
          </p>
        </div>
        
        <div className="max-w-3xl mx-auto bg-card p-6 sm:p-8 rounded-xl border shadow-sm">
          <h2 className="text-2xl font-semibold text-foreground mb-6">Main Pages</h2>
          <ul className="space-y-4">
            {pages.map((page) => (
              <li key={page.path} className="pb-4 border-b last:border-b-0 last:pb-0">
                <Link href={page.path} className="text-xl font-medium text-accent hover:text-primary transition-colors">
                  {page.name}
                </Link>
                <p className="text-muted-foreground mt-1 mb-2 text-sm">
                  {page.description}
                </p>
                <div className="text-xs text-muted-foreground space-y-0.5">
                    <p>
                        Relative Path: <code className="bg-secondary text-secondary-foreground px-1.5 py-0.5 rounded text-xs">{page.path}</code>
                    </p>
                    <p>
                        Full URL: <a href={`${siteUrl}${page.path}`} target="_blank" rel="noopener noreferrer" className="text-primary/80 hover:underline">{`${siteUrl}${page.path}`}</a>
                    </p>
                    <p>Suggested Priority: {page.priority}</p>
                </div>
              </li>
            ))}
          </ul>
        </div>
         <p className="text-center text-muted-foreground mt-10 text-sm max-w-3xl mx-auto">
            <strong>Note for Developers & SEOs:</strong> While this page serves as a human-readable sitemap, search engines typically discover content through an <code className="bg-secondary text-secondary-foreground px-1.5 py-0.5 rounded text-xs">XML sitemap</code> file (usually auto-generated by Next.js at <code className="bg-secondary text-secondary-foreground px-1.5 py-0.5 rounded text-xs">/sitemap.xml</code> if a <code className="bg-secondary text-secondary-foreground px-1.5 py-0.5 rounded text-xs">src/app/sitemap.ts</code> file exists). This HTML page is provided for user convenience.
          </p>
      </div>
    </section>
  );
}
